version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: ecommerce_ci_backend
    ports:
      - "4000:3000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: ecommerce_ci_frontend
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
