version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:4000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
